/* ============================================================
   Sims 4 Mod Builder — XML Generators
   Produces Sims 4 tuning XML from form data
   ============================================================ */

// Utility: create a safe tuning ID from a name
function tuningId(name) {
  return name.replace(/[^a-zA-Z0-9]/g, '_').replace(/_+/g, '_').replace(/^_|_$/g, '');
}

// Utility: generate a pseudo-random instance ID (FNV-1a hash style)
function instanceHash(name) {
  let hash = 0x811c9dc5;
  for (let i = 0; i < name.length; i++) {
    hash ^= name.charCodeAt(i);
    hash = (hash * 0x01000193) >>> 0;
  }
  return '0x' + hash.toString(16).toUpperCase().padStart(16, '0').slice(0, 16);
}

// ----------------------------------------------------------------
// TRAIT XML GENERATOR
// ----------------------------------------------------------------
function generateTraitXML(data) {
  const { name, desc, category, ages, icon, conflicts, buffs } = data;
  const id = tuningId(name);
  const hash = instanceHash(name);

  let xml = `<?xml version="1.0" encoding="utf-8"?>\n`;
  xml += `<!-- Generated by Sims 4 Mod Builder — Stark Studio Labs -->\n`;
  xml += `<!-- Trait: ${name} -->\n\n`;

  xml += `<I c="Trait" i="trait" m="traits.traits" n="${id}" s="${hash}">\n`;

  // Display name
  xml += `  <T n="trait_name">${name}</T>\n`;
  xml += `  <T n="trait_description">${desc}</T>\n`;

  // Category
  xml += `  <E n="trait_type">${category.toUpperCase()}</E>\n`;

  // Ages
  xml += `  <L n="ages">\n`;
  ages.split(', ').forEach(age => {
    xml += `    <E>${age.toUpperCase().replace(/ /g, '_')}</E>\n`;
  });
  xml += `  </L>\n`;

  // Icon reference
  xml += `  <V n="icon" t="enabled">\n`;
  xml += `    <U n="enabled">\n`;
  xml += `      <T n="icon_image">${icon}</T>\n`;
  xml += `    </U>\n`;
  xml += `  </V>\n`;

  // Buffs
  if (buffs.length > 0) {
    xml += `\n  <!-- Buff Effects -->\n`;
    xml += `  <L n="buffs">\n`;
    buffs.forEach(buff => {
      const buffId = tuningId(`buff_${name}_${buff.emotion}`);
      xml += `    <V t="reference">\n`;
      xml += `      <T n="buff_type">${buffId}</T>\n`;
      xml += `    </V>\n`;
    });
    xml += `  </L>\n`;
  }

  // Conflicts
  if (conflicts.length > 0) {
    xml += `\n  <!-- Conflicting Traits -->\n`;
    xml += `  <L n="conflicting_traits">\n`;
    conflicts.forEach(c => {
      xml += `    <T>trait_${tuningId(c)}</T>\n`;
    });
    xml += `  </L>\n`;
  }

  xml += `</I>\n`;

  // Generate buff tuning files
  if (buffs.length > 0) {
    xml += `\n\n`;
    buffs.forEach(buff => {
      const buffId = tuningId(`buff_${name}_${buff.emotion}`);
      const buffHash = instanceHash(buffId);
      xml += `<!-- ===== Buff: ${buff.emotion} ===== -->\n`;
      xml += `<?xml version="1.0" encoding="utf-8"?>\n`;
      xml += `<I c="Buff" i="buff" m="buffs.buffs" n="${buffId}" s="${buffHash}">\n`;
      xml += `  <T n="buff_name">${buff.reason || buff.emotion + ' from ' + name}</T>\n`;
      xml += `  <T n="buff_description">${buff.reason || 'Feeling ' + buff.emotion.toLowerCase()}</T>\n`;
      xml += `  <E n="mood_type">MOOD_${buff.emotion.toUpperCase()}</E>\n`;
      xml += `  <T n="mood_weight">${buff.weight}</T>\n`;
      xml += `  <T n="timeout">0</T>\n`;
      xml += `  <T n="visible">True</T>\n`;
      xml += `</I>\n\n`;
    });
  }

  return xml.trim();
}

// ----------------------------------------------------------------
// CAREER XML GENERATOR
// ----------------------------------------------------------------
function generateCareerXML(data) {
  const { name, desc, track, schedule, levels } = data;
  const id = tuningId(name);
  const hash = instanceHash(name);

  let xml = `<?xml version="1.0" encoding="utf-8"?>\n`;
  xml += `<!-- Generated by Sims 4 Mod Builder — Stark Studio Labs -->\n`;
  xml += `<!-- Career: ${name} -->\n\n`;

  xml += `<I c="Career" i="career" m="careers.career_tuning" n="career_${id}" s="${hash}">\n`;
  xml += `  <T n="career_name">${name}</T>\n`;
  xml += `  <T n="career_description">${desc}</T>\n`;

  // Track type
  xml += `  <E n="career_track_type">${track === 'Branching' ? 'BRANCHING' : 'STANDARD'}</E>\n`;

  // Schedule
  xml += `  <T n="schedule">${schedule}</T>\n`;

  // Career levels
  xml += `\n  <!-- Career Levels -->\n`;
  xml += `  <L n="career_levels">\n`;

  levels.forEach((level, i) => {
    const levelId = tuningId(`${name}_Level_${level.number}`);
    const levelHash = instanceHash(levelId);

    xml += `\n    <!-- Level ${level.number}: ${level.title} -->\n`;
    xml += `    <U>\n`;
    xml += `      <T n="level_name">${level.title}</T>\n`;
    xml += `      <T n="level_description">Level ${level.number} of the ${name} career.</T>\n`;
    xml += `      <T n="simoleons_per_hour">${level.salary}</T>\n`;

    if (level.skill && level.skillReq > 0) {
      xml += `      <V n="promotion_requirement" t="skill">\n`;
      xml += `        <U n="skill">\n`;
      xml += `          <T n="skill_type">skill_${tuningId(level.skill)}</T>\n`;
      xml += `          <T n="skill_level">${level.skillReq}</T>\n`;
      xml += `        </U>\n`;
      xml += `      </V>\n`;
    }

    // Performance metrics
    xml += `      <T n="performance_metrics_per_day">3</T>\n`;

    // Work tone options
    xml += `      <L n="available_tones">\n`;
    xml += `        <E>WORK_HARD</E>\n`;
    xml += `        <E>TAKE_IT_EASY</E>\n`;
    if (i >= 3) {
      xml += `        <E>PRACTICE_SKILLS</E>\n`;
    }
    if (i >= 5) {
      xml += `        <E>NETWORK</E>\n`;
    }
    xml += `      </L>\n`;

    xml += `    </U>\n`;
  });

  xml += `  </L>\n`;
  xml += `</I>\n`;

  return xml.trim();
}

// ----------------------------------------------------------------
// INTERACTION XML GENERATOR
// ----------------------------------------------------------------
function generateInteractionXML(data) {
  const { name, desc, target, category, ages, autonomy, outcomes } = data;
  const id = tuningId(name);
  const hash = instanceHash(name);

  // Determine the base class based on target type
  let baseClass, module;
  switch (target) {
    case 'Sim':
      baseClass = 'SocialSuperInteraction';
      module = 'interactions.social.social_super_interaction';
      break;
    case 'Object':
      baseClass = 'SuperInteraction';
      module = 'interactions.base.super_interaction';
      break;
    case 'Self':
      baseClass = 'SuperInteraction';
      module = 'interactions.base.super_interaction';
      break;
    default:
      baseClass = 'SuperInteraction';
      module = 'interactions.base.super_interaction';
  }

  let xml = `<?xml version="1.0" encoding="utf-8"?>\n`;
  xml += `<!-- Generated by Sims 4 Mod Builder — Stark Studio Labs -->\n`;
  xml += `<!-- Interaction: ${name} -->\n\n`;

  xml += `<I c="${baseClass}" i="interaction" m="${module}" n="${id}" s="${hash}">\n`;
  xml += `  <T n="display_name">${name}</T>\n`;

  if (desc) {
    xml += `  <T n="display_tooltip">${desc}</T>\n`;
  }

  // Category (pie menu)
  xml += `\n  <!-- Pie Menu Category -->\n`;
  xml += `  <V n="category" t="enabled">\n`;
  xml += `    <U n="enabled">\n`;
  xml += `      <E n="pie_menu_category">${category.toUpperCase()}</E>\n`;
  xml += `    </U>\n`;
  xml += `  </V>\n`;

  // Target type
  if (target === 'Sim') {
    xml += `\n  <!-- Target: Other Sim -->\n`;
    xml += `  <E n="target_type">SIM</E>\n`;
  } else if (target === 'Object') {
    xml += `\n  <!-- Target: Object -->\n`;
    xml += `  <E n="target_type">OBJECT</E>\n`;
  }

  // Autonomy
  xml += `\n  <!-- Autonomy -->\n`;
  xml += `  <T n="allow_autonomous">${autonomy === 'true' ? 'True' : 'False'}</T>\n`;

  // Age tests
  xml += `\n  <!-- Age Availability -->\n`;
  xml += `  <V n="test_globals" t="enabled">\n`;
  xml += `    <L n="enabled">\n`;
  xml += `      <V t="age_test">\n`;
  xml += `        <U n="age_test">\n`;
  xml += `          <L n="ages">\n`;
  ages.split(', ').forEach(age => {
    xml += `            <E>${age.toUpperCase().replace(/ /g, '_')}</E>\n`;
  });
  xml += `          </L>\n`;
  xml += `        </U>\n`;
  xml += `      </V>\n`;
  xml += `    </L>\n`;
  xml += `  </V>\n`;

  // Outcomes
  if (outcomes.length > 0) {
    xml += `\n  <!-- Outcome Effects -->\n`;
    xml += `  <L n="basic_extras">\n`;

    outcomes.forEach(outcome => {
      switch (outcome.type) {
        case 'relationship':
          xml += `    <V t="relationship_change">\n`;
          xml += `      <U n="relationship_change">\n`;
          xml += `        <E n="relationship_track">FRIENDSHIP_TRACK</E>\n`;
          xml += `        <T n="amount">${parseOutcomeAmount(outcome.detail, 5)}</T>\n`;
          xml += `        <!-- ${outcome.detail || 'Relationship change'} -->\n`;
          xml += `      </U>\n`;
          xml += `    </V>\n`;
          break;
        case 'skill':
          xml += `    <V t="skill_gain">\n`;
          xml += `      <U n="skill_gain">\n`;
          xml += `        <T n="skill_type">skill_${tuningId(outcome.detail.split(' ')[0] || 'Charisma')}</T>\n`;
          xml += `        <T n="amount">${parseOutcomeAmount(outcome.detail, 10)}</T>\n`;
          xml += `        <!-- ${outcome.detail || 'Skill gain'} -->\n`;
          xml += `      </U>\n`;
          xml += `    </V>\n`;
          break;
        case 'buff':
          xml += `    <V t="buff_apply">\n`;
          xml += `      <U n="buff_apply">\n`;
          xml += `        <T n="buff_type">buff_${tuningId(outcome.detail || 'Happy')}</T>\n`;
          xml += `        <T n="duration">240</T>\n`;
          xml += `        <!-- ${outcome.detail || 'Apply buff'} -->\n`;
          xml += `      </U>\n`;
          xml += `    </V>\n`;
          break;
        case 'need':
          xml += `    <V t="need_change">\n`;
          xml += `      <U n="need_change">\n`;
          xml += `        <E n="need_type">${parseNeedType(outcome.detail)}</E>\n`;
          xml += `        <T n="amount">${parseOutcomeAmount(outcome.detail, 20)}</T>\n`;
          xml += `        <!-- ${outcome.detail || 'Need change'} -->\n`;
          xml += `      </U>\n`;
          xml += `    </V>\n`;
          break;
      }
    });

    xml += `  </L>\n`;
  }

  xml += `</I>\n`;

  // XML Injector snippet
  xml += `\n\n`;
  xml += `<!-- ===== XML Injector Snippet ===== -->\n`;
  xml += `<!-- Add this to inject the interaction into the game -->\n`;
  xml += `<?xml version="1.0" encoding="utf-8"?>\n`;
  xml += `<I c="XmlInjector" i="snippet" m="xml_injector.main" n="xmlinjector_${id}" s="${instanceHash('xmlinjector_' + id)}">\n`;

  if (target === 'Sim') {
    xml += `  <L n="add_interactions_to_sims">\n`;
    xml += `    <U>\n`;
    xml += `      <T n="interaction">${id}</T>\n`;
    xml += `    </U>\n`;
    xml += `  </L>\n`;
  } else {
    xml += `  <L n="add_interactions_to_objects">\n`;
    xml += `    <U>\n`;
    xml += `      <T n="interaction">${id}</T>\n`;
    xml += `      <T n="object"><!-- Target object tuning ID --></T>\n`;
    xml += `    </U>\n`;
    xml += `  </L>\n`;
  }

  xml += `</I>\n`;

  return xml.trim();
}

// ----------------------------------------------------------------
// HELPERS
// ----------------------------------------------------------------

function parseOutcomeAmount(detail, fallback) {
  const match = detail.match(/([+-]?\d+)/);
  return match ? parseInt(match[1]) : fallback;
}

function parseNeedType(detail) {
  const lower = (detail || '').toLowerCase();
  if (lower.includes('fun')) return 'FUN';
  if (lower.includes('social')) return 'SOCIAL';
  if (lower.includes('hunger') || lower.includes('food')) return 'HUNGER';
  if (lower.includes('hygiene') || lower.includes('clean')) return 'HYGIENE';
  if (lower.includes('energy') || lower.includes('sleep')) return 'ENERGY';
  if (lower.includes('bladder')) return 'BLADDER';
  return 'FUN';
}

// CommonJS export for Node.js / Jest (no-op in browser where module is undefined)
if (typeof module !== "undefined" && module.exports) {
  module.exports = {
    tuningId,
    instanceHash,
    generateTraitXML,
    generateCareerXML,
    generateInteractionXML,
    parseOutcomeAmount,
    parseNeedType,
  };
}
